#!/bin/bash

# get directory of this script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# make directory for mounting in containers to share keytabs
mkdir -p $SCRIPT_DIR/../work/keytabs

source $SCRIPT_DIR/setup-docker-kdc.sh

# start docker-kdc
source $SCRIPT_DIR/../work/docker-kdc/kdc start

# copy the keytab to work/keytabs to make it available to other containers
docker cp kdc:/etc/docker-kdc/krb5.keytab $SCRIPT_DIR/../work/keytabs/schema-registry.keytab

# copy krb5.conf generated by docker-kdc to the registry build context
cp $SCRIPT_DIR/../work/docker-kdc/krb5.conf $SCRIPT_DIR/../registry/resources

docker-compose -f $SCRIPT_DIR/../docker-compose.yml up --build -d
