version: '3.7'

services:

  docker-kdc:
    build: docker-kdc
    image: docker-kdc-sr-demo
    volumes:
      - ./work/keytabs:/keytabs:rw
    networks:
      - schema-registry-network

  schema-registry-setup:
    build:
      context: ./registry
      dockerfile: Dockerfile-setup
    image: schema-registry-sr-demo
    networks:
      - schema-registry-network
    depends_on:
      - docker-kdc

  schema-registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    volumes:
      - ./work/keytabs:/keytabs:ro
    networks:
      - schema-registry-network
    depends_on:
      - schema-registry-setup
      - docker-kdc

networks:
  schema-registry-network: