version: '3.7'

services:
#
#  docker-kdc:
#    build: docker-kdc
#    image: docker-kdc-sr-demo
#    volumes:
#      - schema-registry-shared:/etc/docker-kdc
#    networks:
#      - schema-registry-network

  schema-registry-setup:
    build:
      context: ./registry
      dockerfile: Dockerfile-setup
    image: schema-registry-sr-demo
    networks:
      - schema-registry-network
#    depends_on:
#      - docker-kdc

  schema-registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
      network: host
    ports:
      - 9090-9091:9090-9091
    volumes:
      - ./work/keytabs:/keytabs:ro
    networks:
      - schema-registry-network
    depends_on:
      - schema-registry-setup

#volumes:
#  schema-registry-shared:

networks:
  schema-registry-network:
    external: true